name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  provision_agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pulumi/actions
        with:
          args: up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
  build:
    needs: [provision_agents]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $TEST
