name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  provision_agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pulumi/actions
        with:
          args: up
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
      - uses: docker://pulumi/actions
        with:
          args: stack output --json > pulumi.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
      - uses: actions/upload-artifact@v2
        with:
          name: pulumi
          path: pulumi.json
  build_step:
    needs: [provision_agents]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: pulumi
      - uses: montudor/action-zip@v0.1.0
        with:
          args: unzip pulumi.zip
      - run: |
          echo ::set-output name=AWS_BUCKET_NAME::$(jq .bucketName pulumi.json)
        id: aws_output
      - run: echo $AWS_BUCKET_NAME
      - run: yarn build
      # - uses: opspresso/action-s3-sync@master
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     FROM_PATH: app/.cache
      #     DEST_PATH: ${{ steps.aws_output.outputs.AWS_BUCKET_NAME }}
      # - uses: opspresso/action-s3-sync@master
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     FROM_PATH: app/public
      #     DEST_PATH: ${{ steps.aws_output.outputs.AWS_BUCKET_NAME }}
